version: '3.9'

services:

  tweeter-mongodb:
    image: mongo:latest
    container_name: tweeter-mongodb
    restart: always
    volumes:
      - ./mongo/data:/data/db
    ports:
      - 8007:27017

  tweeter-messages-api:
    image: tweeter-messages-api:latest
    restart: always
    depends_on:
      - tweeter-mongodb
    build:
      context: ./
      dockerfile: Api/Dockerfile
    ports:
      - 8000:80    
    environment:
      DB_CONNECTION_STRING: mongodb://tweeter-mongodb:8007
      DB_NAME: tweeter-messages
      ASPNETCORE_ENVIRONMENT: Development
